---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  SECRET_DOMAIN: 192-168-50-60.nip.io 
  SVC_TRAEFIK_ADDR: 192.168.50.60
  METALLB_TRAEFIK_ADDR: 192.168.50.60
  CONFIG_METALLB_RANGE: "192.168.50.60-192.168.50.69"