apiVersion: apps/v1
kind: Deployment
metadata:
  name: mechmarket-nginx
  namespace: default
  labels:
    app: mechmarket-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mechmarket-nginx
  template:
    metadata:
      labels:
        app: mechmarket-nginx
    spec:
      initContainers:
      - name: busybox
        image: alpine/git
        volumeMounts:
          - name: mechmarket-html-volume
            mountPath: /tmp
        command:
        - sh
        - -c
        - git clone --branch mechmarket --single-branch https://github.com/jpconstantineau/jpconstantineau-web.git /tmp && rm -rf /tmp/.git
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
          - name: mechmarket-html-volume
            mountPath: /usr/share/nginx/html
      volumes:
      - name: mechmarket-html-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mechmarket-nginx-service
  namespace: default
spec:
  selector:
    app: mechmarket-nginx
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mechmarket-nginx-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"

spec:
  rules:
  - host: "mechmarket.jpconstantineau.com"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: mechmarket-nginx-service
            port:
              number: 80
  tls:
  - hosts: 
    - mechmarket.jpconstantineau.com
    secretName: mechmarket-jpconstantineau-tls-production