---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  SECRET_DOMAIN: 192-168-50-59.nip.io 
  SVC_TRAEFIK_ADDR: 192.168.50.59
  METALLB_TRAEFIK_ADDR: 192.168.50.59
  METALLB_LB_RANGE: 192.168.50.59