---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  SECRET_DOMAIN: jpto.dev
  SECRET_DOMAIN2: jpconstantineau.com
  SECRET_DOMAIN3: 129-153-66-137.nip.io
  SVC_TRAEFIK_ADDR: 129.153.66.137