---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  SECRET_DOMAIN: jpto.dev
  SECRET_DOMAIN2: jpconstantineau.com
  SECRET_DOMAIN3: 141-148-144-82.nip.io
  SVC_TRAEFIK_ADDR: 141.148.144.82