apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-nginx
  namespace: default
  labels:
    app: store-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-nginx
  template:
    metadata:
      labels:
        app: store-nginx
    spec:
      initContainers:
      - name: busybox
        image: alpine/git
        volumeMounts:
          - name: store-html-volume
            mountPath: /tmp
        command:
        - sh
        - -c
        - git clone --branch store --single-branch https://github.com/jpconstantineau/jpconstantineau-web.git /tmp && rm -rf /tmp/.git
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
          - name: store-html-volume
            mountPath: /usr/share/nginx/html
      volumes:
      - name: store-html-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: store-nginx-service
  namespace: default
spec:
  selector:
    app: store-nginx
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-nginx-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-production
    #traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  rules:
  - host: "store.jpconstantineau.com"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: store-nginx-service
            port:
              number: 80
  tls:
  - hosts: 
    - store.jpconstantineau.com
    secretName: store-jpconstantineau-tls-production